apiVersion: apps/v1
kind: Deployment
metadata:
  name: freekode
  namespace: freekode
  labels:
    app: freekode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freekode
  template:
    metadata:
      labels:
        app: freekode
    spec:
      containers:
      # image name from ecr
      - name: freekode-repo

        # 1. from console: get ecr url 
        image: 850136234717.dkr.ecr.us-east-2.amazonaws.com/freekode-repo:latest 
        imagePullPolicy: "Always"
        # env:
        # - name: REACT_APP_GOOGLE_API
        #   value: "AIzaSyBkXfBuW-KEHGMLXaIC_nVMTDOl3ZZxgps"
          
        # 2. from console: get rds url
        - name:  MYSQL_HOST
          value: "freekode-db.cipyiasonckx.us-east-2.rds.amazonaws.com"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_PASSWORD
          value: "12345678"
        - name: MYSQL_USER
          value: "root"
        # - name: SERP_API
        #   value: "32b7d586045b8f4bf8b17d6d12ca04382c4b7259ddde8918dadddf0bcc6ce3c1"

        # 3. kubectl get svc -nfreekode
        - name: REACT_APP_BASE_URL
          value: "http://a5a9be0eca2c14ebab28d1211a50e42d-1321240743.us-east-2.elb.amazonaws.com/api/"
        resources:
            limits:
              memory: 200Mi
              cpu: 1
            requests:
              memory: 100Mi
              cpu: 100m
        ports:
        - containerPort: 5000
