apiVersion: v1
kind: Service
metadata:
  name: freekode-svc
  namespace: freekode
  labels:
    app: freekode
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: freekode
  type: NodePort
