
name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push docker image to registry
        run: |
          docker build -t app .
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag app freecode23/job-dashboard
          docker push freecode23/job-dashboard
